### ISSUE TITLE
Classes modifications and other modifications not taken in account.   

### ISSUE THREAD

**Issue by Ausborne** [Toni-SM/semu.misc.vscode#3]
Hello @Toni-SM.
First i want to say a big thank you for the extention you provided. It helped me a lot with my work in the last couple months.
But i'm facing an issue with it. When i instanciate a class, and then modify the contents of the class, those modifications are not taken in account when i reexecute my script. Only way to make those modification work is to restart isaacsim. 
![Screenshot from 2023-06-02 10-36-35](https://github.com/Toni-SM/semu.misc.vscode/assets/132055867/8e39180a-0e84-4a7f-adaf-53ca3b39707b)

And after i modify the class : 
![Screenshot from 2023-06-02 10-41-50](https://github.com/Toni-SM/semu.misc.vscode/assets/132055867/bd996419-99e9-49a2-bfaf-a88b972288e1)

After restarting isaacsim : 

![Screenshot from 2023-06-02 10-44-44](https://github.com/Toni-SM/semu.misc.vscode/assets/132055867/d04d4c07-517e-47c7-adca-d9643d86703e)

**Comment by Toni-SM** [comment]
Hi @Ausborne 

Python does not reload previously loaded modules in the same active interpreter execution.

To achieve your goal you need:  
1. Use the Python [`importlib.reload`](https://docs.python.org/3/library/importlib.html#importlib.reload) function
2. Define your class in the same scope as the instance so that when the code is rerun the changes are redefined.

**Comment by Ausborne** [comment]
@Toni-SM  I understand. Thank you for the answer.
